#Multi-Site                                                                                      #- name: Configure splunk cluster master
  shell: /opt/splunk/bin/splunk edit cluster-config -mode {{ cluster_mode }} -multisite {{ mult$
  become: yes
  become_user: splunk
  ignore_errors: yes
  async: 45
  register: config_cluster_master_result
