
- name: Push Conf Files Splunk Server to join Index Cluster and be a Search Head Cluster Member by Copying server.conf
  copy: src=server.conf.multi_site dest=/opt/splunk/etc/apps/org_all_search_base/server.conf.multi_site owner=splunk group=splunk mode=0755
  
- name: Org all Search Base Configure Master URI Multi SIte
  replace:
    path: "/opt/splunk/etc/apps/org_all_search_base/server.conf.multi_site"
    regexp: '<master>'
    replace: "{{ master_internal_ip }}"
    backup: yes

- name: Org all Search Base Configure Deployer URI Multi Site
  replace:
    path: "/opt/splunk/etc/apps/org_all_search_base/server.conf.multi_site"
    regexp: '<deployer>'
    replace: "{{ deployer_internal_ip }}"
    backup: yes

- name: Org all Search Base Configure Master Port Multi SIte
  replace:
    path: "/opt/splunk/etc/apps/org_all_search_base/server.conf.multi_site"
    regexp: '<splunkd_port>'
    replace: "{{ splunkd_port }}"
    backup: yes

- name: Org all Search Base Edit server cluster config for indexer discovery pass4Symm value Multi Site
  replace:
    path: "/opt/splunk/etc/apps/org_all_search_base/server.conf.multi_site"
    regexp: '<idxdiscovery_secret>'
    replace: "{{ idxdiscovery_secret }}"
    backup: yes

- name: Org all Search Base Edit server cluster config for indxer cluster pass4Symm value Multi Site
  replace:
    path: "/opt/splunk/etc/apps/org_all_search_base/server.conf.multi_site"
    regexp: '<idxcluster_secret>'

- name: Org all Search Base Edit server cluster config for search head cluster pass4Symm value Multi Site
  replace:
    path: "/opt/splunk/etc/apps/org_all_search_base/server.conf.multi_site"
    regexp: '<shcluster_secret>'
    replace: "{{ shcluster_secret }}"
    backup: yes

- name: Org all Search Base Configure Server Search Head Cluster Replication Port Mult SIte
  replace:
    path: "/opt/splunk/etc/apps/org_all_search_base/server.conf.multi_site"
    regexp: '<shc_rep_port>'
    replace: "{{ shc_rep_port }}"
    backup: yes
