---
# This playbook will configure Splunk as a cluster master and place base configs in apps directory.
# It relies of having all base configs built already, for information on this,
# please contact Teku Professional Services @ www.tekugroup.net


- name: Copy base configs
  copy: src={{ deploypackages }}{{ base_configs }} dest=/var/tmp owner=splunk group=splunk mode=0755

- name: Edit outputs base config master value
  replace:
    path: "/var/tmp/base_configs/org_all_core_outputs/local/outputs.conf"
    regexp: '<master>'
    replace: "{{ master_internal_ip }}"
    backup: no

- name: Edit outputs base config master value
  replace:
    path: "/var/tmp/base_configs/org_all_core_outputs/local/outputs.conf"
    regexp: '<splunkd_port>'
    replace: "{{ splunkd_port }}"
    backup: no

- name: Edit outputs base config indexer discovery secret value
  replace:
    path: "/var/tmp/base_configs/org_all_core_outputs/local/outputs.conf"
    regexp: '<idxcluster_secret>'
    replace: "{{ idxcluster_secret }}"
    backup: no

- name: Copy global outputs config to app path
  shell: cp -a "/var/tmp/base_configs/org_all_core_outputs" /opt/splunk/etc/apps/

- name: Copy cm role configs to app path
  shell: cp -a "/var/tmp/base_configs/org_cm_base" /opt/splunk/etc/apps/

#Push Server Configs for Master - Single and Multi Site

- name: Push Configure Files for Splunk Cluster Master - Single Site
  copy: src=server.conf dest=/opt/splunk/etc/apps/org_cm_base/local/server.conf owner=splunk group=splunk mode=0755

- name: Push Configure Files for Splunk Cluster Master - Multi Site
  copy: src=server.conf.multi_site dest=/opt/splunk/etc/apps/org_cm_base/local/server.conf.multi_site owner=splunk group=splunk mode=0755

# Single Site Configuration

- name: Org CM Base Configure Site Replication Factor Single Site
  replace:
    path: "/opt/splunk/etc/apps/org_cm_base/local/server.conf"
    regexp: '<replication_factor>'
    replace: "{{ replication_factor }}"
    backup: no

- name: Org CM Base Configure Site Search Factor Single Site
  replace:
    path: "/opt/splunk/etc/apps/org_cm_base/local/server.conf"
    regexp: '<search_factor>'
    replace: "{{ search_factor }}"
    backup: no

- name: Org CM Base Edit server cluster config-indexer discovery secret values Single Site
  replace:
    path: "/opt/splunk/etc/apps/org_cm_base/local/server.conf"
    regexp: '<idxdiscovery_secret>'
    replace: "{{ idxdiscovery_secret }}"
    backup: no

- name: Org CM Base Edit server indexer cluster config  secret values Single Site
  replace:
    path: "/opt/splunk/etc/apps/org_cm_base/local/server.conf"
    regexp: '<idxcluster_secret>'
    replace: "{{ idxcluster_secret }}"
    backup: no

- name: Org CM Base Edit server search cluster config secret pass4symm value Single Site
  replace:
    path: "/opt/splunk/etc/apps/org_cm_base/local/server.conf"
    regexp: '<shcluster_secret>'
    replace: "{{ shcluster_secret }}"
    backup: no

- name:  Org CM Base Edit server cluster config for cluster label Single Site
  replace:
    path: "/opt/splunk/etc/apps/org_cm_base/local/server.conf"
    regexp: '<shcluster_label>'
    replace: "{{ shcluster_label }}"
    backup: no


# Multi Site Configuration 
- name: Org CM Base Configure Site Number Multi SIte
  replace:
    path: "/opt/splunk/etc/apps/org_cm_base/local/server.conf.multi_site"
    regexp: '<master_residence_site>'
    replace: "{{ master_residence_site }}"
    backup: no

- name: Org CM Base Configure MultiSite Status
  replace:
    path: "/opt/splunk/etc/apps/org_cm_base/local/server.conf.multi_site"
    regexp: '<multisite_status>'
    replace: "{{ multisite_status }}"
    backup: no

- name: Org CM Base Configure Available Sites Multi SIte
  replace:
    path: "/opt/splunk/etc/apps/org_cm_base/local/server.conf.multi_site"
    regexp: '<available_sites>'
    replace: "{{ available_sites }}"
    backup: no

- name: Org CM Base Configure Site Replication Factor Multi SIte
  replace:
    path: "/opt/splunk/etc/apps/org_cm_base/local/server.conf.multi_site"
    regexp: '<site_replication_factor>'
    replace: "{{ site_replication_factor }}"
    backup: no

- name: Org CM Base Configure Site Search Factor Multi SIte
  replace:
    path: "/opt/splunk/etc/apps/org_cm_base/local/server.conf.multi_site"
    regexp: '<site_search_factor>'
    replace: "{{ site_search_factor }}"
    backup: no

- name: Org CM Base edit server cluster config-indexer discovery secret values Multi SIte
  replace:
    path: "/opt/splunk/etc/apps/org_cm_base/local/server.conf.multi_site"
    regexp: '<idxdiscovery_secret>'
    replace: "{{ idxdiscovery_secret }}"
    backup: no

- name: Org CM Base Edit server indexer cluster config  secret values Multi SIte
  replace:
    path: "/opt/splunk/etc/apps/org_cm_base/local/server.conf.multi_site"
    regexp: '<idxcluster_secret>'
    replace: "{{ idxcluster_secret }}"
    backup: no

- name: Org CM Base Edit server search cluster config secret pass4symm value Multi SIte
  replace:
    path: "/opt/splunk/etc/apps/org_cm_base/local/server.conf.multi_site"
    regexp: '<shcluster_secret>'
    replace: "{{ shcluster_secret }}"
    backup: no

- name: Org CM Base Edit server cluster config for cluster label Multi Site
  replace:
    path: "/opt/splunk/etc/apps/org_cm_base/local/server.conf.multi_site"
    regexp: '<shcluster_label>'
    replace: "{{ shcluster_label }}"
    backup: no

# Configuration Push and Write to Splunk Hosts

#- name: Fix 'app' permissions
#  file: path=/opt/splunk/etc/apps owner=splunk group=splunk mode=0755 state=directory recurse=yes

- name: Restart Splunk
  shell: /opt/splunk/bin/splunk restart
  become: yes
  become_user: splunk
