# Enable Receiving

- name: Enable Listening
  shell: /opt/splunk/bin/splunk enable listen {{forwarder_listening_port}} -auth {{splkuser}}:{{splkpass}}                                       
  become: yes
  become_user: splunk
  register: indexer_listening 

