---
# This playbook will configure Splunk as an indexer and place base configs in apps directory
# It relies of having all base configs built already, for information on this,
# please contact Teku Professional Services @ www.tekugroup.net

- name: Copy base configs
  copy: src={{ deploypackages }}{{ base_configs }} dest=/var/tmp owner=splunk group=splunk mode=0755

- name: Copy base configs to app path
  copy: src=/var/tmp/base_configs/org_all_indexer_base dest=/opt/splunk/etc/apps owner=splunk group=splunk mode=0755

#Copy Conf Files for Single Site and Multi Site

- name: Configure Splunk Search Peer for Single Site
  copy: src=server.conf dest=/opt/splunk/etc/apps/org_all_indexer_base/server.conf owner=splunk group=splunk mode=0755

- name: Configure Splunk Search Peer for Multi Site
  copy: src=server.conf.multi_site dest=/opt/splunk/etc/apps/org_all_indexer_base/server.conf.multi_site owner=splunk group=splunk mode=0755

# Write Configurations for Single Site Server Config File

- name: Configure Master URI for org all indexer base single site
  replace:
    path: "/opt/splunk/etc/apps/org_all_indexer_base/server.conf"
    regexp: '<master>'
    replace: "{{ master_internal_ip }}"
    backup: yes

- name: Configure Master Port for org all indexer base single site
  replace:
    path: "/opt/splunk/etc/apps/org_all_indexer_base/server.conf"
    regexp: '<splunkd_port>'
    replace: "{{ splunkd_port }}"
    backup: yes

- name: Write org all indexer base Edit server cluster config for index cluster pass4Symm value
  replace:
    path: "/opt/splunk/etc/apps/org_all_indexer_base/server.conf"
    regexp: '<idxcluster_secret>'
    replace: "{{ idxcluster_secret }}"
    backup: yes

- name: Write Org all Indexer Base Configure Replication Port Single Site
  replace:
    path: "/opt/splunk/etc/apps/org_all_indexer_base/server.conf"
    regexp: '<idx_rep_port>'
    replace: "{{ idx_rep_port }}"
    backup: yes

# Write Configurations for Multi Site Server Config File
#- name: Configure Site ID
#  replace:
#    path: "/opt/splunk/etc/apps/org_all_indexer_base/server.conf.multi_site"
#    regexp: '<site_count>'
#    replace: "{{ site_count | int -1 }}"
#    when: site_count.stdout != 0
#    backup: yes
#    ignore_errors: yes

- name: Write for org all indexer base Configure Master URI Multi SIte
  replace:
    path: "/opt/splunk/etc/apps/org_all_indexer_base/server.conf.multi_site"
    regexp: '<master>'
    replace: "{{ master_internal_ip }}"
    backup: yes

- name: Write for org all indexer base Configure Master Port Multi SIte
  replace:
    path: "/opt/splunk/etc/apps/org_all_indexer_base/server.conf.multi_site"
    regexp: '<splunkd_port>'
    replace: "{{ splunkd_port }}"
    backup: yes

- name: Write for org all indexer base  server cluster config for index cluster pass4Symm value multi-site
  replace:
    path: "/opt/splunk/etc/apps/org_all_indexer_base/server.conf.multi_site"
    regexp: '<idxcluster_secret>'
    replace: "{{ idxcluster_secret }}"
    backup: yes

- name: Write for org all indexer base Server Configure Replication Port Multi Site
  replace:
    path: "/opt/splunk/etc/apps/org_all_indexer_base/server.conf.multi_site"
    regexp: '<idx_rep_port>'
    replace: "{{ idx_rep_port }}"
    backup: yes

# Enable Receiving

- name: Enable Listening 
  shell: /opt/splunk/bin/splunk enable listen {{forwarder_listening_port}} -auth {{splkuser}}:{{splkpass}}
  become: yes
  become_user: splunk

# Enable New Configurations to propagate

- name: Restart Splunk
  shell: /opt/splunk/bin/splunk restart
  become: yes
  become_user: splunk
#  async: 45
#  poll: 0

