---
# This role contains plays to configure the License Master

- name: Create license folder
  file:
   path: /opt/splunk/licenses
   owner: splunk
   group: splunk
   mode: 0755
   recurse: yes  

- name: Copy license to License folder
  copy: src=splunk.lic dest=/opt/splunk/licenses/ owner=splunk group=splunk mode=0755
  become: yes
  become_user: splunk

- name: Add Licenese to License Master
  command: /opt/splunk/bin/splunk add licenses /opt/splunk/licenses/splunk.lic -auth {{ splkuser }}:{{ splkpass }}
  become: yes
  become_user: splunk
  register: add_license_to_license_master

- name: Restart Splunk
  command: /opt/splunk/bin/splunk restart --answer-yes
  become: yes
  become_user: splunk
